train:
  id: BankHeistNoFrameskip-v4
  done_on_life_loss: True
  size: 84
  max_episode_steps: null
  
test:
  id: ${..train.id}
  done_on_life_loss: False
  size: ${..train.size}
  max_episode_steps: null

keymap: atari/${.train.id}
